version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: kujira_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - kujira_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kujira_app
    restart: always
    ports:
      - "${API_PORT}:3000"
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - API_PORT=${API_PORT}
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - kujira_network

volumes:
  mongodb_data:

networks:
  kujira_network:
    driver: bridge